//! Explicit boxed fixture index. Payload discovery is intentionally not directory-based.

use crate::build_support::model::BoxedFixtureDef;

macro_rules! fixture {
    ($family:literal, $name:literal) => {
        BoxedFixtureDef {
            name: $name,
            source: include_str!(concat!("../fixtures/boxed/", $family, "/", $name, ".tpz")),
            source_path: concat!("fixtures/boxed/", $family, "/", $name, ".tpz"),
        }
    };
}

/// The E-2 ELIGIBLE set. Every entry is explicit so fixture order and denominator stay fixed.
pub(crate) const FIXTURES: &[BoxedFixtureDef] = &[
    // compatibility
    fixture!("compatibility", "keyword_field_layout_construct_isolation"),
    fixture!("compatibility", "byte_buffer_alias_overlap_snapshot"),
    fixture!("compatibility", "byte_buffer_atomic_range_fault"),
    fixture!("compatibility", "s2_generic_type_alias_substitution"),
    fixture!("compatibility", "s2_unit_typed_match_pattern"),
    fixture!("compatibility", "s2_zero_timeout_single_else_try"),
    fixture!("compatibility", "s2_nested_function_forward_reference"),
    fixture!(
        "compatibility",
        "s2_nested_function_transitive_forward_reference"
    ),
    fixture!(
        "compatibility",
        "s2_nested_function_multistep_forward_reference"
    ),
    fixture!(
        "compatibility",
        "s2_nested_function_branch_forward_reference"
    ),
    fixture!(
        "compatibility",
        "s2_nested_function_dead_branch_forward_reference"
    ),
    fixture!("compatibility", "s2_nested_function_iife_forward_reference"),
    fixture!(
        "compatibility",
        "s2_nested_function_parenthesized_iife_forward_reference"
    ),
    fixture!(
        "compatibility",
        "s2_nested_function_iife_transitive_forward_reference"
    ),
    fixture!(
        "compatibility",
        "s2_nested_function_iife_shadowed_outer_forward_reference"
    ),
    fixture!(
        "compatibility",
        "s2_concurrent_zero_timeout_single_noninstant"
    ),
    fixture!(
        "compatibility",
        "s2_concurrent_zero_timeout_multi_noninstant"
    ),
    fixture!("compatibility", "s2_plain_type_alias_erasure"),
    fixture!("compatibility", "s2_exported_type_alias_erasure"),
    // collections_json
    fixture!("collections_json", "lit_int"),
    fixture!("collections_json", "static_namespace_first_class_core"),
    fixture!("collections_json", "const_fault"),
    fixture!("collections_json", "const_malformed_literal"),
    fixture!("collections_json", "arr_push"),
    fixture!("collections_json", "arr_slice"),
    fixture!("collections_json", "arr_slice_clamp_oob"),
    fixture!("collections_json", "arr_slice_inverted_empty"),
    fixture!("collections_json", "arr_join_strings"),
    fixture!("collections_json", "arr_join_ints"),
    fixture!("collections_json", "arr_index_of_hit"),
    fixture!("collections_json", "arr_index_of_miss"),
    fixture!("collections_json", "arr_index_of_pipe"),
    fixture!("collections_json", "arr_slice_pipe"),
    fixture!("collections_json", "arr_join_pipe"),
    fixture!("collections_json", "arr_stdlib_substring"),
    fixture!("collections_json", "str_starts_with_hit"),
    fixture!("collections_json", "str_starts_with_miss"),
    fixture!("collections_json", "str_starts_with_empty"),
    fixture!("collections_json", "str_ends_with_hit"),
    fixture!("collections_json", "str_ends_with_miss"),
    fixture!("collections_json", "str_ends_with_empty"),
    fixture!("collections_json", "str_contains_hit"),
    fixture!("collections_json", "str_contains_miss"),
    fixture!("collections_json", "str_index_of_hit"),
    fixture!("collections_json", "str_index_of_miss"),
    fixture!("collections_json", "str_index_of_empty"),
    fixture!("collections_json", "str_index_of_scalar"),
    fixture!("collections_json", "str_last_index_of_hit"),
    fixture!("collections_json", "str_last_index_of_miss"),
    fixture!("collections_json", "str_last_index_of_empty"),
    fixture!("collections_json", "str_last_index_of_scalar"),
    fixture!("collections_json", "str_replace_basic"),
    fixture!("collections_json", "str_replace_non_overlapping"),
    fixture!("collections_json", "str_replace_no_match"),
    fixture!("collections_json", "str_trim"),
    fixture!("collections_json", "str_trim_start"),
    fixture!("collections_json", "str_trim_end"),
    fixture!("collections_json", "str_trim_ws_set"),
    fixture!("collections_json", "str_split_basic"),
    fixture!("collections_json", "str_split_consecutive"),
    fixture!("collections_json", "str_split_trailing"),
    fixture!("collections_json", "str_split_empty_input"),
    fixture!("collections_json", "str_split_no_match"),
    fixture!("collections_json", "str_split_multichar"),
    fixture!("collections_json", "str_split_empty_sep_faults"),
    fixture!("collections_json", "str_method_pipe"),
    fixture!("collections_json", "str_ends_with_first_class"),
    fixture!("collections_json", "str_last_index_of_first_class"),
    fixture!("collections_json", "str_replace_first_class"),
    fixture!("collections_json", "to_int_radix"),
    fixture!("collections_json", "to_int_radix_named"),
    fixture!("collections_json", "to_int_radix_firstclass"),
    fixture!("collections_json", "to_int_radix_pipe"),
    fixture!("collections_json", "to_float"),
    fixture!("collections_json", "to_float_firstclass"),
    fixture!("collections_json", "to_float_named"),
    fixture!("collections_json", "hangul_identifiers"),
    fixture!("collections_json", "str_bytelength"),
    fixture!("collections_json", "arr_sorted_int"),
    fixture!("collections_json", "arr_sorted_hangul"),
    fixture!("collections_json", "arr_sorted_nonmutating"),
    fixture!("collections_json", "str_codepointat"),
    fixture!("collections_json", "from_code_point"),
    fixture!("collections_json", "from_code_point_roundtrip"),
    fixture!("collections_json", "from_code_point_named"),
    fixture!("collections_json", "map_insert"),
    fixture!("collections_json", "set_add"),
    fixture!("collections_json", "map_remove"),
    fixture!("collections_json", "set_remove"),
    fixture!("collections_json", "set_contains"),
    fixture!("collections_json", "set_contains_miss"),
    fixture!("collections_json", "map_contains_key"),
    fixture!("collections_json", "map_contains_key_miss"),
    fixture!("collections_json", "map_values"),
    fixture!("collections_json", "map_length"),
    fixture!("collections_json", "set_length"),
    fixture!("collections_json", "map_entries"),
    fixture!("collections_json", "map_is_empty_true"),
    fixture!("collections_json", "map_is_empty_false"),
    fixture!("collections_json", "set_is_empty_true"),
    fixture!("collections_json", "set_is_empty_false"),
    fixture!("collections_json", "set_to_array"),
    fixture!("collections_json", "set_union"),
    fixture!("collections_json", "set_intersection"),
    fixture!("collections_json", "set_difference"),
    fixture!("collections_json", "map_clear"),
    fixture!("collections_json", "set_clear"),
    fixture!("collections_json", "map_clear_immutable"),
    fixture!("collections_json", "set_clear_immutable"),
    fixture!("collections_json", "map_update_present"),
    fixture!("collections_json", "map_update_present_order"),
    fixture!("collections_json", "map_update_absent"),
    fixture!("collections_json", "map_update_absent_order"),
    fixture!("collections_json", "map_update_immutable"),
    fixture!("collections_json", "map_map_values"),
    fixture!("collections_json", "map_map_values_keys"),
    fixture!(
        "collections_json",
        "map_map_values_callback_mutates_source_alias"
    ),
    fixture!("collections_json", "map_filter"),
    fixture!("collections_json", "map_filter_values"),
    fixture!("collections_json", "map_update_callback_fault"),
    fixture!("collections_json", "map_map_values_callback_fault"),
    fixture!("collections_json", "map_filter_callback_fault"),
    fixture!("collections_json", "array_pop"),
    fixture!("collections_json", "array_pop_then_array"),
    fixture!("collections_json", "array_pop_empty"),
    fixture!("collections_json", "array_clear"),
    fixture!("collections_json", "array_clear_immutable"),
    fixture!("collections_json", "array_reverse"),
    fixture!("collections_json", "array_reverse_immutable"),
    fixture!("collections_json", "array_insert_mid"),
    fixture!("collections_json", "array_insert_end"),
    fixture!("collections_json", "array_insert_front"),
    fixture!("collections_json", "array_insert_out_of_range"),
    fixture!("collections_json", "array_insert_negative"),
    fixture!("collections_json", "array_insert_immutable"),
    fixture!("collections_json", "array_remove_at"),
    fixture!("collections_json", "array_remove_at_then_array"),
    fixture!("collections_json", "array_remove_at_out_of_range"),
    fixture!("collections_json", "array_remove_at_negative"),
    fixture!("collections_json", "array_remove_at_immutable"),
    fixture!("collections_json", "array_sort"),
    fixture!("collections_json", "array_sort_strings"),
    fixture!("collections_json", "array_sort_matches_sorted"),
    fixture!("collections_json", "array_sort_immutable"),
    fixture!("collections_json", "array_sort_by"),
    fixture!("collections_json", "array_sort_by_field"),
    fixture!("collections_json", "array_sort_by_matches_sorted_by"),
    fixture!("collections_json", "array_sort_by_immutable"),
    fixture!("collections_json", "array_retain"),
    fixture!("collections_json", "array_retain_all"),
    fixture!("collections_json", "array_retain_none"),
    fixture!("collections_json", "array_retain_callback_fault"),
    fixture!("collections_json", "array_retain_immutable"),
    fixture!("collections_json", "array_sort_aliasing"),
    fixture!("collections_json", "array_reverse_aliasing"),
    fixture!("collections_json", "json_stringify_record"),
    fixture!("collections_json", "json_stringify_array"),
    fixture!("collections_json", "json_stringify_typed_empty_array"),
    fixture!("collections_json", "json_stringify_nested"),
    fixture!("collections_json", "json_stringify_string_escape"),
    fixture!("collections_json", "json_stringify_float_err"),
    fixture!("collections_json", "json_stringify_set_err"),
    fixture!("collections_json", "json_stringify_named"),
    fixture!("collections_json", "json_stringify_nominal_record"),
    fixture!("collections_json", "json_stringify_enum_payloadless"),
    fixture!("collections_json", "json_stringify_enum_payload"),
    fixture!("collections_json", "json_stringify_newtype_transparent"),
    fixture!("collections_json", "json_stringify_newtype_over_string"),
    fixture!("collections_json", "json_stringify_record_of_enum"),
    fixture!("collections_json", "json_stringify_enum_of_record"),
    fixture!("collections_json", "json_stringify_array_of_record"),
    fixture!(
        "collections_json",
        "json_stringify_nominal_nonencodable_err"
    ),
    fixture!("collections_json", "json_parseas_int"),
    fixture!("collections_json", "json_parseas_string"),
    fixture!("collections_json", "json_parseas_bool"),
    fixture!("collections_json", "json_parseas_unit"),
    fixture!("collections_json", "json_parseas_array"),
    fixture!("collections_json", "json_parseas_option_null"),
    fixture!("collections_json", "json_parseas_map"),
    fixture!("collections_json", "json_parseas_struct_record"),
    fixture!("collections_json", "json_parseas_nominal_record"),
    fixture!("collections_json", "json_parseas_generic_nominal_record"),
    fixture!(
        "collections_json",
        "json_parseas_nested_generic_nominal_record"
    ),
    fixture!("collections_json", "json_parseas_generic_nominal_enum"),
    fixture!("collections_json", "json_parseas_generic_nominal_newtype"),
    fixture!(
        "collections_json",
        "json_parseas_generic_capture_record_wrappers"
    ),
    fixture!(
        "collections_json",
        "json_parseas_generic_capture_enum_payload"
    ),
    fixture!(
        "collections_json",
        "json_parseas_generic_capture_newtype_base"
    ),
    fixture!(
        "collections_json",
        "json_parseas_generic_substituted_map_key"
    ),
    fixture!("collections_json", "json_parseas_root_alias"),
    fixture!("collections_json", "json_parseas_generic_root_alias"),
    fixture!("collections_json", "json_parseas_aliases_in_nominal_fields"),
    fixture!("collections_json", "json_parseas_enum_payload"),
    fixture!("collections_json", "json_parseas_newtype"),
    fixture!("collections_json", "json_parseas_int_float_err"),
    fixture!("collections_json", "json_decode_struct_record"),
    fixture!("collections_json", "json_parseas_pipe"),
    // namespaces
    fixture!("namespaces", "math_sqrt_ok"),
    fixture!("namespaces", "math_sqrt_perfect"),
    fixture!("namespaces", "math_sqrt_zero"),
    fixture!("namespaces", "math_sqrt_neg_err"),
    fixture!("namespaces", "math_abs"),
    fixture!("namespaces", "math_abs_neg_zero"),
    fixture!("namespaces", "math_floor"),
    fixture!("namespaces", "math_floor_neg"),
    fixture!("namespaces", "math_ceil"),
    fixture!("namespaces", "math_ceil_neg"),
    fixture!("namespaces", "math_round_half_up"),
    fixture!("namespaces", "math_round_half_down_neg"),
    fixture!("namespaces", "math_round_half_zero"),
    fixture!("namespaces", "math_round_down"),
    fixture!("namespaces", "math_sin_half_pi"),
    fixture!("namespaces", "math_cos_pi"),
    fixture!("namespaces", "math_tan_quarter_pi"),
    fixture!("namespaces", "math_min"),
    fixture!("namespaces", "math_max"),
    fixture!("namespaces", "math_min_nan_first"),
    fixture!("namespaces", "math_is_nan_false"),
    fixture!("namespaces", "math_is_nan_true"),
    fixture!("namespaces", "math_is_finite_true"),
    fixture!("namespaces", "math_is_finite_inf"),
    fixture!("namespaces", "math_is_finite_nan"),
    fixture!("namespaces", "math_parse_float_ok"),
    fixture!("namespaces", "math_parse_float_trim"),
    fixture!("namespaces", "math_parse_float_trim_int"),
    fixture!("namespaces", "math_parse_float_exp"),
    fixture!("namespaces", "math_parse_float_err"),
    fixture!("namespaces", "math_parse_float_empty_err"),
    fixture!("namespaces", "math_parse_float_trailing_err"),
    fixture!("namespaces", "math_parse_float_inf_err"),
    fixture!("namespaces", "math_parse_float_infinity_err"),
    fixture!("namespaces", "math_parse_float_nan_err"),
    fixture!("namespaces", "math_abs_nan_is_nan"),
    fixture!("namespaces", "math_named_arg"),
    fixture!("namespaces", "math_min_named"),
    fixture!("namespaces", "math_min_named_source_order"),
    fixture!("namespaces", "math_max_mixed"),
    fixture!("namespaces", "bytes_encode_render"),
    fixture!("namespaces", "bytes_encode_empty_render"),
    fixture!("namespaces", "bytes_to_hex"),
    fixture!("namespaces", "bytes_to_hex_empty"),
    fixture!("namespaces", "bytes_b64_empty"),
    fixture!("namespaces", "bytes_b64_f"),
    fixture!("namespaces", "bytes_b64_fo"),
    fixture!("namespaces", "bytes_b64_foo"),
    fixture!("namespaces", "bytes_b64_foob"),
    fixture!("namespaces", "bytes_b64_fooba"),
    fixture!("namespaces", "bytes_b64_foobar"),
    fixture!("namespaces", "bytes_from_hex_ok"),
    fixture!("namespaces", "bytes_from_hex_odd_err"),
    fixture!("namespaces", "bytes_from_hex_nonhex_err"),
    fixture!("namespaces", "bytes_from_b64_ok"),
    fixture!("namespaces", "bytes_from_b64_badlen_err"),
    fixture!("namespaces", "bytes_from_b64_badchar_err"),
    fixture!("namespaces", "bytes_from_b64_badpad_err"),
    fixture!("namespaces", "bytes_b64_roundtrip"),
    fixture!("namespaces", "bytes_hex_roundtrip"),
    fixture!("namespaces", "bytes_decode_ok"),
    fixture!("namespaces", "bytes_decode_invalid_err"),
    fixture!("namespaces", "bytes_empty_static"),
    fixture!("namespaces", "bytes_from_array_ok"),
    fixture!("namespaces", "bytes_from_array_bad"),
    fixture!("namespaces", "bytes_get_to_array"),
    fixture!("namespaces", "bytes_length"),
    fixture!("namespaces", "bytes_length_method_value"),
    fixture!("namespaces", "bytes_decode_method_value"),
    fixture!("namespaces", "bytes_to_hex_method_value"),
    fixture!("namespaces", "bytes_to_base64_method_value"),
    fixture!("namespaces", "bytes_slice_method_value"),
    fixture!("namespaces", "bytes_slice"),
    fixture!("namespaces", "bytes_slice_clamp_oob"),
    fixture!("namespaces", "bytes_slice_inverted_empty"),
    fixture!("namespaces", "bytes_concat"),
    fixture!("namespaces", "bytes_eq_true"),
    fixture!("namespaces", "bytes_eq_false"),
    fixture!("namespaces", "bytes_order_lt"),
    fixture!("namespaces", "bytes_order_le"),
    fixture!("namespaces", "bytes_order_gt"),
    fixture!("namespaces", "bytes_order_ge"),
    fixture!("namespaces", "bytes_in_array"),
    fixture!("namespaces", "bytes_in_set"),
    fixture!("namespaces", "bytes_sorted"),
    fixture!("namespaces", "bytes_set_key"),
    fixture!("namespaces", "bytes_map_key"),
    fixture!("namespaces", "bytes_named_arg"),
    fixture!("namespaces", "bytes_concat_named"),
    fixture!("namespaces", "encoding_hex_encode"),
    fixture!("namespaces", "encoding_base64_roundtrip"),
    fixture!("namespaces", "encoding_named_args"),
    fixture!("namespaces", "encoding_method_value_unchecked"),
    fixture!("namespaces", "codec_gzip_empty_canonical_hex"),
    fixture!("namespaces", "codec_gzip_hello_canonical_hex"),
    fixture!("namespaces", "codec_gzip_roundtrip"),
    fixture!("namespaces", "codec_gzip_named"),
    fixture!("namespaces", "codec_gzip_method_value_unchecked"),
    fixture!("namespaces", "codec_deflate_empty_canonical_hex"),
    fixture!("namespaces", "codec_deflate_fixed_empty_canonical_hex"),
    fixture!("namespaces", "codec_deflate_fixed_hello_canonical_hex"),
    fixture!("namespaces", "codec_deflate_fixed_method_value_unchecked"),
    fixture!("namespaces", "codec_zlib_fixed_empty"),
    fixture!("namespaces", "codec_zlib_fixed_named"),
    fixture!("namespaces", "codec_zlib_fixed_method_value_unchecked"),
    fixture!("namespaces", "codec_reed_solomon_one_byte_canonical"),
    fixture!("namespaces", "codec_reed_solomon_empty_refusal"),
    fixture!("namespaces", "codec_reed_solomon_method_value_unchecked"),
    fixture!("namespaces", "codec_deflate_roundtrip"),
    fixture!("namespaces", "codec_deflate_named"),
    fixture!("namespaces", "codec_deflate_method_value_unchecked"),
    fixture!("namespaces", "codec_zstd_empty_canonical_hex"),
    fixture!("namespaces", "codec_zstd_hello_canonical_hex"),
    fixture!("namespaces", "codec_zstd_roundtrip"),
    fixture!("namespaces", "codec_zstd_named_level"),
    fixture!("namespaces", "codec_zstd_named_source_order"),
    fixture!("namespaces", "codec_zstd_invalid_level"),
    fixture!("namespaces", "codec_zstd_method_value_unchecked"),
    fixture!("namespaces", "std_math_codec_imports"),
    fixture!("namespaces", "hash_sha256_empty"),
    fixture!("namespaces", "hash_sha256_abc"),
    fixture!("namespaces", "hash_sha256_named_multiblock"),
    fixture!("namespaces", "hash_sha512_abc"),
    fixture!("namespaces", "hash_hmac_sha256_rfc4231_tc2"),
    fixture!("namespaces", "hash_hmac_sha256_named"),
    fixture!("namespaces", "hash_sha256_method_value_unchecked"),
    fixture!("namespaces", "hash_crc32_check_value"),
    fixture!("namespaces", "hash_crc32_named_binary"),
    fixture!("namespaces", "hash_crc32_method_value_unchecked"),
    fixture!("namespaces", "path_from_to_string"),
    fixture!("namespaces", "path_join"),
    fixture!("namespaces", "path_parent_file_extension"),
    fixture!("namespaces", "path_with_extension"),
    fixture!("namespaces", "path_reject_escape"),
    fixture!("namespaces", "path_method_value_unchecked"),
    fixture!("namespaces", "path_static_value_unchecked"),
    fixture!("namespaces", "cli_has_flag"),
    fixture!("namespaces", "cli_option"),
    fixture!("namespaces", "cli_options"),
    fixture!("namespaces", "cli_positionals"),
    fixture!("namespaces", "cli_static_value_unchecked"),
    fixture!("namespaces", "regex_is_match"),
    fixture!("namespaces", "regex_find_scalar_offsets"),
    fixture!("namespaces", "regex_find_all"),
    fixture!("namespaces", "regex_split"),
    fixture!("namespaces", "regex_replace_all"),
    fixture!("namespaces", "regex_named_groups_json"),
    fixture!("namespaces", "regex_compile_err"),
    fixture!("namespaces", "regex_unsupported_escape_err"),
    fixture!("namespaces", "regex_alternation"),
    fixture!("namespaces", "regex_static_value_unchecked"),
    fixture!("namespaces", "regex_method_value_unchecked"),
    fixture!("namespaces", "csv_parse_json"),
    fixture!("namespaces", "csv_parse_with_header_json"),
    fixture!("namespaces", "csv_stringify_quotes"),
    fixture!(
        "namespaces",
        "csv_stringify_with_header_static_value_unchecked"
    ),
    fixture!("namespaces", "toml_parse_to_json"),
    fixture!("namespaces", "toml_from_json_stringify"),
    fixture!("namespaces", "toml_static_values_unchecked"),
    fixture!("namespaces", "url_parse_accessors"),
    fixture!("namespaces", "url_static_value_unchecked"),
    fixture!("namespaces", "url_method_value_unchecked"),
    fixture!("namespaces", "url_annotation_key_and_sorted"),
    fixture!("namespaces", "date_from_ymd_accessors"),
    fixture!("namespaces", "date_parse_iso_invalid_err"),
    fixture!("namespaces", "date_static_value_unchecked"),
    fixture!("namespaces", "date_method_value_unchecked"),
    fixture!("namespaces", "date_annotation_key_and_sorted"),
    fixture!("namespaces", "bigint_parse_ops"),
    fixture!("namespaces", "bigint_div_mod_zero"),
    fixture!("namespaces", "bigint_static_value_unchecked"),
    fixture!("namespaces", "bigint_method_value_unchecked"),
    fixture!("namespaces", "bigint_annotation_key_and_sorted"),
    fixture!("namespaces", "decimal_parse_accessors"),
    fixture!("namespaces", "decimal_ops"),
    fixture!("namespaces", "decimal_static_value_unchecked"),
    fixture!("namespaces", "decimal_method_value_unchecked"),
    fixture!("namespaces", "decimal_annotation_key_and_sorted"),
    fixture!("namespaces", "decimal_round_modes"),
    fixture!("namespaces", "decimal_round_named_args"),
    fixture!("namespaces", "decimal_div_rounding"),
    fixture!("namespaces", "decimal_div_zero_err"),
    fixture!("namespaces", "decimal_round_method_value_unchecked"),
    // runtime_dispatch
    fixture!("runtime_dispatch", "mutator_field_shadow"),
    fixture!("runtime_dispatch", "mutator_uncomparable_key"),
    fixture!("runtime_dispatch", "file_read"),
    fixture!("runtime_dispatch", "file_write"),
    fixture!("runtime_dispatch", "file_write_named_call_forms"),
    fixture!("runtime_dispatch", "file_write_named_field_shadow_forms"),
    fixture!("runtime_dispatch", "receiver_builtin_named_call_forms"),
    fixture!(
        "runtime_dispatch",
        "receiver_builtin_named_field_shadow_forms"
    ),
    fixture!("runtime_dispatch", "byte_buffer_named_pipe_mutators"),
    fixture!("runtime_dispatch", "ok_or_first_class_receiver_value"),
    fixture!("runtime_dispatch", "first_class_receiver_method_mutator"),
    fixture!("runtime_dispatch", "first_class_receiver_array_callbacks"),
    fixture!(
        "runtime_dispatch",
        "first_class_receiver_array_callback_mutators"
    ),
    fixture!("runtime_dispatch", "first_class_receiver_map_callbacks"),
    fixture!(
        "runtime_dispatch",
        "first_class_receiver_option_result_callbacks"
    ),
    fixture!("runtime_dispatch", "first_class_receiver_resource_methods"),
    fixture!(
        "runtime_dispatch",
        "first_class_receiver_pipe_and_optional_values"
    ),
    fixture!(
        "runtime_dispatch",
        "first_class_receiver_optional_none_mutator_short_circuit"
    ),
    fixture!("runtime_dispatch", "first_class_receiver_field_shadow"),
    fixture!(
        "runtime_dispatch",
        "first_class_receiver_wrong_type_precedes_mutability"
    ),
    fixture!("runtime_dispatch", "file_open_missing"),
    fixture!("runtime_dispatch", "file_close_then_read"),
    fixture!(
        "runtime_dispatch",
        "using_resource_closes_before_later_closure"
    ),
    fixture!(
        "runtime_dispatch",
        "using_resource_question_closes_before_later_closure"
    ),
    fixture!(
        "runtime_dispatch",
        "using_resource_return_closes_before_later_closure"
    ),
    fixture!(
        "runtime_dispatch",
        "using_resource_break_closes_before_later_closure"
    ),
    fixture!(
        "runtime_dispatch",
        "using_resource_continue_closes_before_later_closure"
    ),
    fixture!(
        "runtime_dispatch",
        "using_resource_body_defer_runs_before_close"
    ),
    fixture!(
        "runtime_dispatch",
        "using_resource_initializer_once_and_body_tail_discarded"
    ),
    fixture!("runtime_dispatch", "optional_file_read_some"),
    fixture!("runtime_dispatch", "optional_file_write_some"),
    fixture!("runtime_dispatch", "optional_file_none_short_circuits"),
    fixture!("runtime_dispatch", "pipe_optional_file_write"),
    fixture!("runtime_dispatch", "optional_file_write_type_fault"),
    fixture!("runtime_dispatch", "pipe_get_indexes"),
    fixture!("runtime_dispatch", "pipe_okor_bridge"),
    fixture!("runtime_dispatch", "pipe_member_field_shadow"),
    fixture!("runtime_dispatch", "pipe_member_eval_order"),
    fixture!("runtime_dispatch", "pipe_resource_write"),
    fixture!("runtime_dispatch", "pipe_resource_read_arity_fault"),
    fixture!("runtime_dispatch", "pipe_mutator_push"),
    fixture!("runtime_dispatch", "pipe_mutator_immutable_fault"),
    fixture!(
        "runtime_dispatch",
        "pipe_optional_mutator_remove_at_immutable_fault"
    ),
    fixture!("runtime_dispatch", "pipe_mutator_field_shadow"),
    fixture!("runtime_dispatch", "pipe_okorelse_some"),
    fixture!("runtime_dispatch", "pipe_okorelse_none"),
    fixture!("runtime_dispatch", "pipe_okorelse_arity_fault"),
    fixture!("runtime_dispatch", "preflight_mutator"),
    fixture!("runtime_dispatch", "preflight_resource"),
    fixture!("runtime_dispatch", "preflight_get"),
    fixture!("runtime_dispatch", "preflight_optional"),
    fixture!("runtime_dispatch", "mutator_field_shadow_immutable"),
    fixture!("runtime_dispatch", "mutator_immutable_collection"),
    fixture!("runtime_dispatch", "mutator_clear_wrong_type_immutable"),
    fixture!("runtime_dispatch", "map_update_wrong_type_immutable"),
    fixture!("runtime_dispatch", "option_bridge_okor"),
    fixture!("runtime_dispatch", "option_okorelse_lazy_some"),
    fixture!("runtime_dispatch", "option_okorelse_lazy_none"),
    fixture!("runtime_dispatch", "option_optional_bridge"),
    fixture!("runtime_dispatch", "option_optional_bridge_pipe"),
    fixture!("runtime_dispatch", "option_optional_okorelse_arg_eval"),
    fixture!("runtime_dispatch", "option_okorelse_arity_direct"),
    fixture!("runtime_dispatch", "option_okorelse_arity_optional"),
    fixture!("runtime_dispatch", "option_okorelse_arity_pipe"),
    fixture!("runtime_dispatch", "option_okorelse_record_multiarg"),
    fixture!("runtime_dispatch", "option_okorelse_named_f"),
    fixture!("runtime_dispatch", "option_okorelse_named_field"),
    fixture!("runtime_dispatch", "option_okorelse_named_mismatch"),
    fixture!("runtime_dispatch", "option_okorelse_named_wrong"),
    fixture!("runtime_dispatch", "option_okorelse_named_twice"),
    fixture!("runtime_dispatch", "option_okorelse_named_multi"),
    fixture!("runtime_dispatch", "preflight_okor"),
    fixture!("runtime_dispatch", "preflight_okorelse"),
    fixture!("runtime_dispatch", "preflight_pipe"),
    fixture!("runtime_dispatch", "preflight_pipe_optional"),
    fixture!("runtime_dispatch", "tpl_p_normalize"),
    fixture!("runtime_dispatch", "tpl_sql_diagnostic"),
    fixture!("runtime_dispatch", "tpl_interpolation"),
    fixture!("runtime_dispatch", "tpl_in_interp"),
    fixture!("runtime_dispatch", "mutator_get_interp"),
    fixture!("runtime_dispatch", "nested_template"),
    fixture!("runtime_dispatch", "template_accessors"),
    fixture!("runtime_dispatch", "file_read_interp"),
    fixture!("runtime_dispatch", "mutator_field_path"),
    fixture!("runtime_dispatch", "mutator_index_path"),
    fixture!("runtime_dispatch", "index_assign_basic"),
    fixture!("runtime_dispatch", "index_assign_reads_rhs"),
    fixture!("runtime_dispatch", "index_assign_compound"),
    fixture!("runtime_dispatch", "index_assign_coalesce"),
    fixture!("runtime_dispatch", "index_assign_nested"),
    fixture!("runtime_dispatch", "index_assign_oob"),
    fixture!("runtime_dispatch", "index_assign_non_int"),
    fixture!("runtime_dispatch", "index_assign_non_array"),
    fixture!("runtime_dispatch", "index_assign_compound_fault"),
    fixture!("runtime_dispatch", "index_assign_nonident_root"),
    fixture!("runtime_dispatch", "index_assign_immutable_root"),
    fixture!("runtime_dispatch", "record_path_assign"),
    fixture!("runtime_dispatch", "record_path_nested"),
    fixture!("runtime_dispatch", "record_path_compound"),
    fixture!("runtime_dispatch", "record_path_coalesce_null"),
    fixture!("runtime_dispatch", "record_path_coalesce_present"),
    fixture!("runtime_dispatch", "record_path_no_field_fault"),
    fixture!("runtime_dispatch", "record_path_non_record_fault"),
    fixture!(
        "runtime_dispatch",
        "record_path_compound_rhs_mutates_sibling"
    ),
    fixture!("runtime_dispatch", "record_path_rebind_seen_by_closure"),
    fixture!("runtime_dispatch", "cell_path_assign"),
    fixture!("runtime_dispatch", "cell_path_compound"),
    fixture!("runtime_dispatch", "cell_path_coalesce_null"),
    fixture!("runtime_dispatch", "cell_path_coalesce_present"),
    fixture!("runtime_dispatch", "cell_path_nested"),
    fixture!("runtime_dispatch", "cell_path_compound_rhs_mutates_cell"),
    fixture!("runtime_dispatch", "cell_path_oob_fault"),
    fixture!("runtime_dispatch", "cell_path_non_int_index"),
    fixture!("runtime_dispatch", "cell_path_no_field_fault"),
    fixture!("runtime_dispatch", "cell_path_immutable_root"),
    fixture!("runtime_dispatch", "cell_path_nonident_root"),
    fixture!("runtime_dispatch", "alias_typed_let"),
    fixture!("runtime_dispatch", "alias_typed_for"),
    fixture!("runtime_dispatch", "alias_typed_record"),
    fixture!("runtime_dispatch", "alias_typed_container"),
    fixture!("runtime_dispatch", "alias_chain"),
    fixture!("runtime_dispatch", "alias_in_union"),
    fixture!("runtime_dispatch", "alias_typed_let_mismatch"),
    fixture!("runtime_dispatch", "alias_under_type_param_conforms"),
    fixture!("runtime_dispatch", "alias_under_type_param_faults"),
    fixture!("runtime_dispatch", "call_type_args_explicit"),
    fixture!("runtime_dispatch", "call_type_args_inferred"),
    fixture!("runtime_dispatch", "call_type_args_static_set"),
    fixture!("runtime_dispatch", "call_type_args_filter_explicit"),
    fixture!("runtime_dispatch", "call_type_args_receiver_map_explicit"),
    fixture!("runtime_dispatch", "call_type_args_receiver_pipe_explicit"),
    fixture!("runtime_dispatch", "mutator_field_path_immutable"),
    fixture!("runtime_dispatch", "mutator_nonident_root"),
    fixture!("runtime_dispatch", "mutator_optional_path"),
    fixture!("runtime_dispatch", "mutator_optional_immutable"),
    fixture!("runtime_dispatch", "mutator_pipe_optional"),
    fixture!("runtime_dispatch", "mutator_pipe_optional_immutable"),
    fixture!("runtime_dispatch", "concurrent_join"),
    fixture!("runtime_dispatch", "concurrent_cross_arm_stdout"),
    fixture!("runtime_dispatch", "concurrent_recursion_within_limit"),
    fixture!("runtime_dispatch", "concurrent_recursion_isolated_arms"),
    fixture!("runtime_dispatch", "concurrent_two_while_arms"),
    fixture!("runtime_dispatch", "concurrent_three_arms"),
    fixture!("runtime_dispatch", "concurrent_fault"),
    fixture!("runtime_dispatch", "concurrent_timeout_record"),
    fixture!("runtime_dispatch", "concurrent_timeout_fault"),
    fixture!("runtime_dispatch", "concurrent_timeout_else_multi"),
    // core_control
    fixture!("core_control", "lit_float"),
    fixture!("core_control", "lit_string"),
    fixture!("core_control", "lit_bool_unit_null"),
    fixture!("core_control", "arith_precedence"),
    fixture!("core_control", "unary_neg"),
    fixture!("core_control", "comparison_true"),
    fixture!("core_control", "comparison_false"),
    fixture!("core_control", "string_concat"),
    fixture!("core_control", "fault_div_zero"),
    fixture!("core_control", "fault_overflow"),
    fixture!("core_control", "sequence_tail_value"),
    fixture!("core_control", "non_tail_fault_wins"),
    fixture!("core_control", "array_literal"),
    fixture!("core_control", "record_literal"),
    fixture!("core_control", "nested_aggregate"),
    fixture!("core_control", "let_binding"),
    fixture!("core_control", "let_used_in_op"),
    fixture!("core_control", "mutable_rebind"),
    fixture!("core_control", "let_in_aggregate"),
    fixture!("core_control", "block_value"),
    fixture!("core_control", "if_true_branch"),
    fixture!("core_control", "if_false_branch"),
    fixture!("core_control", "if_no_else_taken"),
    fixture!("core_control", "if_no_else_skipped"),
    fixture!("core_control", "else_if_chain"),
    fixture!("core_control", "nested_block_shadows"),
    fixture!("core_control", "outer_binding_in_block"),
    fixture!("core_control", "block_mutates_outer"),
    fixture!("core_control", "fault_in_taken_branch"),
    fixture!("core_control", "if_condition_not_bool"),
    fixture!("core_control", "shadow_does_not_mutate_outer"),
    fixture!("core_control", "while_sum"),
    fixture!("core_control", "while_never_runs"),
    fixture!("core_control", "while_with_break"),
    fixture!("core_control", "while_with_continue"),
    fixture!("core_control", "nested_while_break_targets_inner"),
    fixture!("core_control", "while_body_let_is_per_iteration"),
    fixture!("core_control", "fault_in_while_cond"),
    fixture!("core_control", "loop_break_value"),
    fixture!("core_control", "loop_search_break_value"),
    fixture!("core_control", "loop_labeled_break_nested"),
    fixture!("core_control", "loop_valueless_unit"),
    fixture!("core_control", "loop_break_value_join"),
    fixture!("core_control", "loop_defer_runs_on_break"),
    fixture!("core_control", "loop_labeled_continue"),
    fixture!("core_control", "loop_nested_while_passthrough"),
    fixture!("core_control", "loop_break_contextual_option"),
    fixture!("core_control", "loop_break_value_before_defer_drain"),
    fixture!("core_control", "loop_break_int_literals_widen"),
    fixture!("core_control", "loop_duplicate_label_shadows_nearest"),
    fixture!(
        "core_control",
        "loop_valueless_break_value_evaluated_discarded"
    ),
    fixture!("core_control", "for_stmt_sum"),
    fixture!("core_control", "for_expr_collect"),
    fixture!("core_control", "nested_for_expr"),
    fixture!("core_control", "for_expr_labeled_break_to_outer_loop"),
    fixture!("core_control", "for_stmt_with_break"),
    fixture!("core_control", "for_stmt_with_continue"),
    fixture!("core_control", "for_body_let_per_iteration"),
    fixture!("core_control", "for_body_let_shadows_outer"),
    fixture!("core_control", "nested_for_stmt_break_inner"),
    fixture!("core_control", "for_not_iterable_fault"),
    fixture!("core_control", "for_over_range"),
    fixture!("core_control", "for_expr_over_range"),
    fixture!("core_control", "for_destructure_aliased_body_mutation"),
    fixture!("core_control", "for_list_destructure"),
    fixture!("core_control", "for_record_destructure_stmt"),
    fixture!("core_control", "for_ctor_destructure_stmt"),
    fixture!("core_control", "for_nested_list_ctor"),
    fixture!("core_control", "for_ctor_typed_subpattern"),
    fixture!("core_control", "for_destructure_length_fault"),
    fixture!("core_control", "for_ctor_none_fault"),
    fixture!("core_control", "for_range_with_step"),
    fixture!("core_control", "range_exclusive_endpoint"),
    fixture!("core_control", "range_in_step_member"),
    fixture!("core_control", "range_in_step_nonmember"),
    fixture!("core_control", "range_in_full_span_no_overflow"),
    fixture!("core_control", "range_in_full_span_descending_no_overflow"),
    fixture!("core_control", "range_descending_is_empty"),
    fixture!("core_control", "range_step_zero_fault"),
    fixture!("core_control", "print_hello"),
    fixture!("core_control", "print_twice"),
    fixture!("core_control", "print_in_loop"),
    fixture!("core_control", "print_a_computed_string"),
    fixture!("core_control", "print_in_a_branch"),
    fixture!("core_control", "print_string_only_fault"),
    fixture!("core_control", "print_in_expression_for"),
    fixture!("core_control", "match_literal_first"),
    fixture!("core_control", "match_literal_middle"),
    fixture!("core_control", "match_literal_catch_all"),
    fixture!("core_control", "match_binding"),
    fixture!("core_control", "match_string"),
    fixture!("core_control", "match_bool"),
    fixture!("core_control", "match_float_literal"),
    fixture!("core_control", "nested_match"),
    fixture!("core_control", "match_value_then_print"),
    fixture!("core_control", "match_miss_fault"),
    fixture!("core_control", "or_pattern_ctor_result"),
    fixture!("core_control", "or_pattern_ctor_option"),
    fixture!("core_control", "or_pattern_wildcard"),
    fixture!("core_control", "or_bind_result_ok"),
    fixture!("core_control", "or_bind_result_err"),
    fixture!("core_control", "or_bind_guard_hit"),
    fixture!("core_control", "or_bind_guard_skip"),
    fixture!("core_control", "or_bind_guard_first_alt"),
    fixture!("core_control", "or_bind_nested_ctor_payload"),
    fixture!("core_control", "or_bind_nested_ctor_payload_guard"),
    fixture!("core_control", "or_bind_exhaustive_no_catchall"),
    fixture!("core_control", "match_nested_rest"),
    fixture!("core_control", "match_nested_rest_prefix_suffix"),
    fixture!("core_control", "match_nested_rest_len_mismatch"),
    fixture!("core_control", "match_nested_rest_recursive"),
    fixture!("core_control", "let_nested_rest"),
    fixture!("core_control", "let_nested_rest_prefix_suffix"),
    fixture!("core_control", "match_nested_rest_aliased_mutation"),
    fixture!("core_control", "match_nested_rest_constructor_fallthrough"),
    fixture!("core_control", "match_nested_list_aliased_mutation"),
    fixture!("core_control", "match_simple_list_aliased_mutation"),
    fixture!("core_control", "match_rest_list_aliased_mutation"),
    fixture!("core_control", "match_ctor_nested_list_alias"),
    fixture!("core_control", "match_record_nested_list_alias"),
    fixture!("core_control", "match_guard_false_falls_through"),
    fixture!("core_control", "match_guard_mutates_alias_true"),
    fixture!("core_control", "match_guard_mutates_alias_false"),
    fixture!("core_control", "match_rest_nested_prefix"),
    fixture!("core_control", "match_rest_nested_suffix"),
    fixture!("core_control", "match_rest_nested_aliased_mutation"),
    fixture!("core_control", "destructure_rest_nested_prefix"),
    fixture!("core_control", "destructure_rest_nested_fault"),
    fixture!("core_control", "destructure_rest_nested_suffix"),
    // functions_hof
    fixture!("functions_hof", "to_int_success"),
    fixture!("functions_hof", "to_int_negative_trimmed"),
    fixture!("functions_hof", "to_int_failure"),
    fixture!("functions_hof", "to_int_empty"),
    fixture!("functions_hof", "to_int_non_string_fault"),
    fixture!("functions_hof", "input_empty_value"),
    fixture!("functions_hof", "input_interpolated"),
    fixture!("functions_hof", "input_first_class"),
    fixture!("functions_hof", "input_first_class_arity_fault"),
    fixture!("functions_hof", "input_direct_arity_fault"),
    fixture!("functions_hof", "named_builtin_print"),
    fixture!("functions_hof", "named_builtin_toint"),
    fixture!("functions_hof", "named_builtin_map"),
    fixture!("functions_hof", "named_builtin_reduce_reordered"),
    fixture!("functions_hof", "named_builtin_partial"),
    fixture!("functions_hof", "named_builtin_wrong_name_fault"),
    fixture!("functions_hof", "named_builtin_filter"),
    fixture!("functions_hof", "named_builtin_given_twice_fault"),
    fixture!("functions_hof", "named_builtin_missing_fault"),
    fixture!("functions_hof", "named_builtin_local_shadow"),
    fixture!("functions_hof", "named_builtin_sideeffect_order"),
    fixture!("functions_hof", "interp_int"),
    fixture!("functions_hof", "interp_local"),
    fixture!("functions_hof", "interp_string"),
    fixture!("functions_hof", "interp_multiple"),
    fixture!("functions_hof", "interp_bool"),
    fixture!("functions_hof", "interp_in_print"),
    fixture!("functions_hof", "interp_fault"),
    fixture!("functions_hof", "lambda_call_simple"),
    fixture!("functions_hof", "lambda_call_two_params"),
    fixture!("functions_hof", "lambda_call_zero_params"),
    fixture!("functions_hof", "lambda_with_if"),
    fixture!("functions_hof", "lambda_calls_print"),
    fixture!("functions_hof", "lambda_with_interpolation"),
    fixture!("functions_hof", "nested_lambda_call"),
    fixture!("functions_hof", "capture_immutable"),
    fixture!("functions_hof", "capture_multiple"),
    fixture!("functions_hof", "capture_in_print"),
    fixture!("functions_hof", "capture_in_interpolation"),
    fixture!("functions_hof", "nested_capture"),
    fixture!("functions_hof", "capture_innermost_shadow"),
    fixture!("functions_hof", "indirect_call"),
    fixture!("functions_hof", "indirect_call_two_params"),
    fixture!("functions_hof", "indirect_call_of_a_capture"),
    fixture!("functions_hof", "call_returned_closure"),
    fixture!("functions_hof", "arity_too_few"),
    fixture!("functions_hof", "arity_too_many"),
    fixture!("functions_hof", "call_non_closure"),
    fixture!("functions_hof", "map_double"),
    fixture!("functions_hof", "filter_even"),
    fixture!("functions_hof", "reduce_sum"),
    fixture!("functions_hof", "array_filter_receiver"),
    fixture!("functions_hof", "array_filter_capture"),
    fixture!("functions_hof", "array_filter_shadow"),
    fixture!("functions_hof", "array_filter_callback_fault"),
    fixture!("functions_hof", "array_map_receiver"),
    fixture!("functions_hof", "array_map_to_string"),
    fixture!("functions_hof", "array_reduce_receiver"),
    fixture!("functions_hof", "array_map_shadow"),
    fixture!("functions_hof", "option_map_some"),
    fixture!("functions_hof", "option_map_none"),
    fixture!("functions_hof", "option_map_lazy_none"),
    fixture!("functions_hof", "option_map_some_fault"),
    fixture!("functions_hof", "option_map_string"),
    fixture!("functions_hof", "option_map_none_evaluates_arg"),
    fixture!("functions_hof", "option_flatmap_some"),
    fixture!("functions_hof", "option_flatmap_some_to_none"),
    fixture!("functions_hof", "option_flatmap_none"),
    fixture!("functions_hof", "option_flatmap_chain"),
    fixture!("functions_hof", "option_flatmap_none_evaluates_arg"),
    fixture!("functions_hof", "result_map_ok"),
    fixture!("functions_hof", "result_map_err"),
    fixture!("functions_hof", "result_map_err_lazy"),
    fixture!("functions_hof", "result_map_string"),
    fixture!("functions_hof", "result_flatmap_ok"),
    fixture!("functions_hof", "result_flatmap_err"),
    fixture!("functions_hof", "result_flatmap_chain"),
    fixture!("functions_hof", "result_flatmap_err_lazy"),
    fixture!("functions_hof", "array_map_named"),
    fixture!("functions_hof", "array_filter_named"),
    fixture!("functions_hof", "option_map_named"),
    fixture!("functions_hof", "option_flatmap_named"),
    fixture!("functions_hof", "result_map_named"),
    fixture!("functions_hof", "map_named_shadow_match"),
    fixture!("functions_hof", "map_named_shadow_mismatch"),
    fixture!("functions_hof", "reduce_named_in_order"),
    fixture!("functions_hof", "reduce_named_reordered"),
    fixture!("functions_hof", "reduce_named_mixed"),
    fixture!("functions_hof", "reduce_named_source_order"),
    fixture!("functions_hof", "reduce_named_shadow_match"),
    fixture!("functions_hof", "reduce_named_shadow_mismatch"),
    fixture!("functions_hof", "json_parse_array"),
    fixture!("functions_hof", "json_parse_object_sorted"),
    fixture!("functions_hof", "json_parse_unicode_escape"),
    fixture!("functions_hof", "json_parse_number_lexemes"),
    fixture!("functions_hof", "json_parse_leading_zero_err"),
    fixture!("functions_hof", "json_parse_duplicate_key_err"),
    fixture!("functions_hof", "json_accessor_array"),
    fixture!("functions_hof", "json_accessor_exact_int"),
    fixture!("functions_hof", "json_accessor_frac_not_int"),
    fixture!("functions_hof", "json_accessor_scalar"),
    fixture!("functions_hof", "json_asint_scale_down"),
    fixture!("functions_hof", "json_asint_i64_min"),
    fixture!("functions_hof", "json_asint_zero_huge_exp"),
    fixture!("functions_hof", "json_iter_object"),
    fixture!("functions_hof", "json_iter_array"),
    fixture!("functions_hof", "exptype_let_option_none"),
    fixture!("functions_hof", "exptype_return_none"),
    fixture!("functions_hof", "exptype_empty_array"),
    fixture!("functions_hof", "exptype_return_ok"),
    fixture!("functions_hof", "exptype_if_join"),
    fixture!("functions_hof", "exptype_map_new"),
    fixture!("functions_hof", "enum_decl_inert"),
    fixture!("functions_hof", "enum_decl_payload_parses"),
    fixture!("functions_hof", "enum_is_contextual_ident"),
    fixture!("functions_hof", "map_with_capture"),
    fixture!("functions_hof", "map_then_reduce"),
    fixture!("functions_hof", "map_non_iterable_fault"),
    fixture!("functions_hof", "filter_predicate_not_bool_fault"),
    fixture!("functions_hof", "array_of"),
    fixture!("functions_hof", "array_of_empty"),
    fixture!("functions_hof", "array_of_spread"),
    fixture!("functions_hof", "array_of_mixed_spread"),
    fixture!("functions_hof", "array_of_double_spread"),
    fixture!("functions_hof", "array_of_spread_empty"),
    fixture!("functions_hof", "set_of_spread_via_for"),
    fixture!("functions_hof", "array_of_bad_spread"),
    fixture!("functions_hof", "set_of_spread_nonhashable"),
    fixture!("functions_hof", "recursion_within_limit"),
    fixture!("functions_hof", "recursion_over_limit_faults"),
    fixture!("functions_hof", "recursion_sequential_calls_ok"),
    fixture!("functions_hof", "recursion_mutual_within_limit"),
    fixture!("functions_hof", "set_of_via_for"),
    fixture!("functions_hof", "set_of_dedup"),
    fixture!("functions_hof", "set_of_with_map"),
    fixture!("functions_hof", "map_new_for_faults"),
    fixture!("functions_hof", "map_of_entries_get"),
    fixture!("functions_hof", "map_of_entries_duplicate_later_wins"),
    fixture!("functions_hof", "map_of_entries_entries_snapshot"),
    fixture!("functions_hof", "map_of_entries_named"),
    fixture!("functions_hof", "map_of_entries_static_value_unchecked"),
    fixture!("functions_hof", "map_of_entries_non_keyable_fault"),
    fixture!("functions_hof", "set_of_non_hashable_fault"),
    fixture!("functions_hof", "function_call"),
    fixture!("functions_hof", "function_with_local"),
    fixture!("functions_hof", "function_with_if"),
    fixture!("functions_hof", "function_calls_function"),
    fixture!("functions_hof", "function_passed_to_map"),
    fixture!("functions_hof", "function_arity_fault"),
    fixture!("functions_hof", "generic_identity_int"),
    fixture!("functions_hof", "generic_identity_string"),
    fixture!("functions_hof", "generic_pair"),
    fixture!("functions_hof", "generic_nested_call"),
    fixture!("functions_hof", "generic_result_propagation"),
    fixture!("functions_hof", "hof_map_reduce_chain"),
    fixture!("functions_hof", "string_scalars_count_interp"),
    fixture!("functions_hof", "result_question_chain"),
    fixture!("functions_hof", "generic_two_type_params"),
    fixture!("functions_hof", "generic_typed_let_erases"),
    fixture!("functions_hof", "generic_typed_let_array_erases"),
    fixture!("functions_hof", "generic_wraps_some"),
    fixture!("functions_hof", "generic_array_param"),
    fixture!("functions_hof", "variadic_collects"),
    fixture!("functions_hof", "variadic_empty"),
    fixture!("functions_hof", "variadic_after_fixed"),
    fixture!("functions_hof", "variadic_only_fixed_supplied"),
    fixture!("functions_hof", "variadic_missing_fixed_faults"),
    fixture!("functions_hof", "variadic_length"),
    fixture!("functions_hof", "variadic_with_default_fixed"),
    fixture!("functions_hof", "call_spread_nontrailing"),
    fixture!("functions_hof", "call_spread_double"),
    fixture!("functions_hof", "call_spread_then_positional"),
    fixture!("functions_hof", "call_spread_pre_positional"),
    fixture!("functions_hof", "call_spread_requires_variadic"),
    fixture!("functions_hof", "call_spread_skip_unsatisfied"),
    fixture!("functions_hof", "call_spread_empty_then_positional"),
    fixture!("functions_hof", "call_spread_empty_pure"),
    fixture!("functions_hof", "spread_named"),
    fixture!("functions_hof", "spread_named_with_positional"),
    fixture!("functions_hof", "spread_named_given_twice_fault"),
    fixture!("functions_hof", "spread_named_missing_fault"),
    fixture!("functions_hof", "spread_named_nonvariadic_fault"),
    fixture!("functions_hof", "spread_named_cannot_skip_priority"),
    fixture!("functions_hof", "spread_named_noncallable_fault"),
    fixture!("functions_hof", "spread_named_bad_spread_no_sideeffect"),
    fixture!("functions_hof", "spread_named_variadic_surplus_given_twice"),
    fixture!("functions_hof", "spread_named_builtin_value_nopar"),
    fixture!("functions_hof", "spread_named_builtin_value_missing"),
    fixture!("functions_hof", "spread_named_builtin_value_reqvar"),
    fixture!("functions_hof", "spread_composed_variadic_left"),
    fixture!("functions_hof", "spread_named_composed_nopar"),
    fixture!("functions_hof", "spread_named_post_spread_positional"),
    fixture!("functions_hof", "spread_named_multi_spread"),
    fixture!("functions_hof", "spread_named_interleaved"),
    fixture!("functions_hof", "spread_named_bad_nonfirst_spread"),
    fixture!("functions_hof", "entry_export_value"),
    fixture!("functions_hof", "entry_export_fn_forward"),
    fixture!("functions_hof", "entry_export_type_noop"),
    // destructuring
    fixture!("destructuring", "destructure_list"),
    fixture!("destructuring", "destructure_list_wildcard"),
    fixture!("destructuring", "destructure_list_len_mismatch"),
    fixture!("destructuring", "destructure_list_nonarray"),
    fixture!("destructuring", "destructure_list_single"),
    fixture!("destructuring", "destructure_chained"),
    fixture!("destructuring", "destructure_record"),
    fixture!("destructuring", "destructure_record_rename"),
    fixture!("destructuring", "destructure_record_subset"),
    fixture!("destructuring", "destructure_record_wildcard"),
    fixture!("destructuring", "destructure_record_missing"),
    fixture!("destructuring", "destructure_record_nonrecord"),
    fixture!("destructuring", "destructure_rest_head"),
    fixture!("destructuring", "destructure_rest_tail"),
    fixture!("destructuring", "destructure_rest_last"),
    fixture!("destructuring", "destructure_rest_init"),
    fixture!("destructuring", "destructure_rest_middle"),
    fixture!("destructuring", "destructure_rest_empty_middle"),
    fixture!("destructuring", "destructure_rest_anon"),
    fixture!("destructuring", "destructure_rest_whole"),
    fixture!("destructuring", "destructure_rest_exact_min"),
    fixture!("destructuring", "destructure_rest_too_short"),
    fixture!("destructuring", "destructure_record_nested_some"),
    fixture!("destructuring", "destructure_record_nested_ok"),
    fixture!("destructuring", "destructure_record_nested_mixed"),
    fixture!("destructuring", "destructure_record_nested_none_faults"),
    fixture!("destructuring", "destructure_record_nested_literal"),
    fixture!("destructuring", "destructure_record_nested_literal_faults"),
    fixture!("destructuring", "destructure_record_nested_deep_ctor"),
    fixture!("destructuring", "destructure_list_nested_some"),
    fixture!("destructuring", "destructure_list_nested_literal"),
    fixture!("destructuring", "destructure_list_nested_literal_miss"),
    fixture!("destructuring", "destructure_list_nested_some_miss"),
    fixture!("destructuring", "destructure_list_nested_deep"),
    fixture!("destructuring", "destructure_list_nested_len_miss"),
    fixture!("destructuring", "match_record_in_record"),
    fixture!("destructuring", "match_list_in_list"),
    fixture!("destructuring", "match_record_in_ctor"),
    fixture!("destructuring", "match_list_in_record"),
    fixture!("destructuring", "match_nested_inner_miss"),
    fixture!("destructuring", "destructure_record_in_record"),
    fixture!("destructuring", "destructure_list_in_list"),
    fixture!("destructuring", "destructure_list_in_record"),
    fixture!("destructuring", "destructure_record_in_list"),
    fixture!("destructuring", "match_typed_subpat_int"),
    fixture!("destructuring", "match_typed_subpat_miss"),
    fixture!("destructuring", "match_typed_subpat_union"),
    fixture!("destructuring", "match_typed_subpat_in_list"),
    fixture!("destructuring", "match_typed_subpat_result"),
    fixture!("destructuring", "destructure_typed_subpat"),
    fixture!("destructuring", "destructure_typed_subpat_miss"),
    fixture!("destructuring", "destructure_nested_rest"),
    fixture!("destructuring", "match_nested_rest"),
    fixture!("destructuring", "destructure_nested_rest_init"),
    fixture!("destructuring", "match_rest_in_ctor"),
    fixture!("destructuring", "destructure_nested_rest_empty"),
    fixture!("destructuring", "match_nested_rest_short"),
    // expressions_calls
    fixture!("expressions_calls", "function_with_print"),
    fixture!("expressions_calls", "nested_function_captures_enclosing"),
    fixture!("expressions_calls", "nested_function_shadows_outer_mutable"),
    fixture!(
        "expressions_calls",
        "nested_function_block_shadow_assignment"
    ),
    fixture!(
        "expressions_calls",
        "nested_function_block_shadow_read_after_local_assignment"
    ),
    fixture!("expressions_calls", "record_field"),
    fixture!("expressions_calls", "array_literal_length"),
    fixture!("expressions_calls", "nested_record_field"),
    fixture!("expressions_calls", "map_new_keys"),
    fixture!("expressions_calls", "record_missing_field_fault"),
    fixture!("expressions_calls", "string_length_fault"),
    fixture!("expressions_calls", "and_false_short_circuits"),
    fixture!("expressions_calls", "and_true_returns_rhs"),
    fixture!("expressions_calls", "and_true_returns_non_bool_rhs"),
    fixture!("expressions_calls", "or_true_short_circuits"),
    fixture!("expressions_calls", "or_false_returns_rhs"),
    fixture!("expressions_calls", "or_false_returns_non_bool_rhs"),
    fixture!("expressions_calls", "and_non_bool_lhs_fault"),
    fixture!("expressions_calls", "coalesce_null_uses_rhs"),
    fixture!("expressions_calls", "coalesce_passthrough_is_lazy"),
    fixture!("expressions_calls", "coalesce_some_unwraps"),
    fixture!("expressions_calls", "coalesce_none_uses_rhs"),
    fixture!("expressions_calls", "to_int_as_value"),
    fixture!("expressions_calls", "to_int_as_value_none"),
    fixture!("expressions_calls", "to_int_in_map"),
    fixture!("expressions_calls", "to_int_arity_fault"),
    fixture!("expressions_calls", "to_int_type_fault"),
    fixture!("expressions_calls", "to_int_via_pipe"),
    fixture!("expressions_calls", "to_int_via_compose"),
    fixture!("expressions_calls", "print_as_value"),
    fixture!("expressions_calls", "print_in_map"),
    fixture!("expressions_calls", "print_arity_fault"),
    fixture!("expressions_calls", "print_type_fault"),
    fixture!("expressions_calls", "print_via_pipe"),
    fixture!("expressions_calls", "open_direct_err"),
    fixture!("expressions_calls", "open_as_value_err"),
    fixture!("expressions_calls", "open_type_fault"),
    fixture!("expressions_calls", "open_arity_fault"),
    fixture!("expressions_calls", "map_as_value"),
    fixture!("expressions_calls", "filter_as_value"),
    fixture!("expressions_calls", "reduce_as_value"),
    fixture!("expressions_calls", "map_as_value_arity"),
    fixture!("expressions_calls", "map_via_pipe"),
    fixture!("expressions_calls", "const_basic"),
    fixture!("expressions_calls", "const_forward_ref"),
    fixture!("expressions_calls", "const_chain"),
    fixture!("expressions_calls", "const_in_function"),
    fixture!("expressions_calls", "const_typed"),
    fixture!("expressions_calls", "const_string"),
    fixture!("expressions_calls", "some_constructor"),
    fixture!("expressions_calls", "ok_constructor"),
    fixture!("expressions_calls", "err_constructor"),
    fixture!("expressions_calls", "nested_some"),
    fixture!("expressions_calls", "some_via_coalesce"),
    fixture!("expressions_calls", "shadowed_some_is_a_call"),
    fixture!("expressions_calls", "none_value"),
    fixture!("expressions_calls", "none_let_read"),
    fixture!("expressions_calls", "none_via_coalesce"),
    fixture!("expressions_calls", "none_double_coalesce"),
    fixture!("expressions_calls", "none_in_lambda"),
    fixture!("expressions_calls", "none_record_value"),
    fixture!("expressions_calls", "try_ok_unwraps"),
    fixture!("expressions_calls", "try_err_propagates"),
    fixture!("expressions_calls", "try_non_result_faults"),
    fixture!("expressions_calls", "try_chain_ok"),
    fixture!("expressions_calls", "try_chain_short_circuits"),
    fixture!("expressions_calls", "try_in_lambda_tail"),
    fixture!("expressions_calls", "try_wraps_in_some"),
    fixture!("expressions_calls", "compose_basic"),
    fixture!("expressions_calls", "compose_order_matters"),
    fixture!("expressions_calls", "compose_inline"),
    fixture!("expressions_calls", "compose_three_chain"),
    fixture!("expressions_calls", "compose_inner_arity_fault"),
    fixture!("expressions_calls", "compose_not_callable"),
    fixture!("expressions_calls", "compose_capturing_lambdas"),
    fixture!("expressions_calls", "pipe_unary"),
    fixture!("expressions_calls", "pipe_chain"),
    fixture!("expressions_calls", "pipe_call_insert"),
    fixture!("expressions_calls", "pipe_call_insert_two"),
    fixture!("expressions_calls", "pipe_inline_lambda"),
    fixture!("expressions_calls", "pipe_capturing"),
    fixture!("expressions_calls", "pipe_not_callable"),
    fixture!("expressions_calls", "pipe_arity_fault"),
    fixture!("expressions_calls", "pipe_field_record"),
    fixture!("expressions_calls", "pipe_field_chain"),
    fixture!("expressions_calls", "pipe_field_array_length"),
    fixture!("expressions_calls", "pipe_field_missing"),
    fixture!("expressions_calls", "pipe_field_map_keys"),
    fixture!("expressions_calls", "pipe_placeholder_second"),
    fixture!("expressions_calls", "pipe_placeholder_first"),
    fixture!("expressions_calls", "pipe_placeholder_twice"),
    fixture!("expressions_calls", "pipe_placeholder_lambda"),
    fixture!("expressions_calls", "pipe_placeholder_chain"),
    fixture!("expressions_calls", "pipe_placeholder_argument_expressions"),
    fixture!("expressions_calls", "pipe_method_array_get"),
    fixture!("expressions_calls", "pipe_method_array_get_oob"),
    fixture!("expressions_calls", "pipe_method_map_get"),
    fixture!("expressions_calls", "pipe_method_arity_fault"),
    fixture!("expressions_calls", "pipe_method_scalars_faults"),
    fixture!("expressions_calls", "pipe_receiver_hof_map"),
    fixture!("expressions_calls", "pipe_receiver_hof_filter"),
    fixture!("expressions_calls", "pipe_receiver_hof_reduce"),
    fixture!("expressions_calls", "pipe_receiver_hof_flatmap_option"),
    fixture!("expressions_calls", "pipe_receiver_hof_sortedby"),
    fixture!("expressions_calls", "pipe_receiver_hof_map_shadow"),
    fixture!("expressions_calls", "pipe_receiver_hof_mapvalues"),
    fixture!("expressions_calls", "pipe_receiver_hof_update"),
    fixture!("expressions_calls", "pipe_receiver_hof_sortby"),
    fixture!("expressions_calls", "pipe_receiver_hof_retain"),
    fixture!("expressions_calls", "pipe_opt_call_some"),
    fixture!("expressions_calls", "pipe_opt_call_none"),
    fixture!("expressions_calls", "pipe_opt_call_plain"),
    fixture!("expressions_calls", "pipe_opt_call_builtin"),
    fixture!("expressions_calls", "default_param_used"),
    fixture!("expressions_calls", "default_param_supplied"),
    fixture!("expressions_calls", "default_param_all"),
    fixture!("expressions_calls", "default_param_partial"),
    fixture!("expressions_calls", "default_param_neg_int"),
    fixture!("expressions_calls", "default_param_neg_int_supplied"),
    fixture!("expressions_calls", "default_param_neg_float"),
    fixture!("expressions_calls", "default_param_not_bool"),
    fixture!("expressions_calls", "default_param_paren_neg"),
    fixture!("expressions_calls", "default_param_missing_required"),
    fixture!("expressions_calls", "default_param_bool"),
    fixture!("expressions_calls", "default_param_float"),
    fixture!("expressions_calls", "default_param_string"),
    fixture!("expressions_calls", "default_param_string_supplied"),
    fixture!("expressions_calls", "default_param_mixed"),
    fixture!("expressions_calls", "named_arg_basic"),
    fixture!("expressions_calls", "named_arg_mixed"),
    fixture!("expressions_calls", "named_arg_with_default"),
    fixture!("expressions_calls", "named_arg_default_filled"),
    fixture!("expressions_calls", "named_arg_unknown"),
    fixture!("expressions_calls", "named_arg_twice"),
    fixture!("expressions_calls", "named_arg_lambda"),
    fixture!("expressions_calls", "named_arg_composed"),
    fixture!("expressions_calls", "named_arg_builtin"),
    fixture!("expressions_calls", "match_return_arm"),
    fixture!("expressions_calls", "match_return_not_taken"),
    fixture!("expressions_calls", "match_return_bare"),
    fixture!("expressions_calls", "match_return_binding"),
    fixture!("expressions_calls", "match_return_guarded"),
    fixture!("expressions_calls", "match_return_all_arms"),
    fixture!("expressions_calls", "type_alias_noop"),
    fixture!("expressions_calls", "type_alias_then_let"),
    fixture!("expressions_calls", "type_alias_mid"),
    fixture!("expressions_calls", "type_alias_record_type"),
    fixture!("expressions_calls", "type_alias_last_unit"),
    fixture!("expressions_calls", "array_index"),
    fixture!("expressions_calls", "array_index_var"),
    fixture!("expressions_calls", "nested_array_index"),
    fixture!("expressions_calls", "array_index_oob_fault"),
    fixture!("expressions_calls", "array_index_negative_fault"),
    fixture!("expressions_calls", "string_not_indexable_fault"),
    fixture!("expressions_calls", "index_non_array_fault"),
    fixture!("expressions_calls", "compound_add"),
    fixture!("expressions_calls", "compound_sub_mul"),
    fixture!("expressions_calls", "compound_div_rem"),
    fixture!("expressions_calls", "compound_accumulate_in_loop"),
    fixture!("expressions_calls", "compound_div_by_zero_fault"),
    fixture!("expressions_calls", "coalesce_assign_null"),
    fixture!("expressions_calls", "coalesce_assign_keeps_value"),
    fixture!("expressions_calls", "coalesce_assign_is_lazy"),
    fixture!("expressions_calls", "coalesce_assign_none"),
    fixture!("expressions_calls", "array_spread_basic"),
    fixture!("expressions_calls", "array_spread_multiple"),
    fixture!("expressions_calls", "array_spread_empty"),
    fixture!("expressions_calls", "array_spread_literal"),
    fixture!("expressions_calls", "array_spread_non_array_fault"),
    fixture!("expressions_calls", "array_spread_in_for"),
    fixture!("expressions_calls", "array_spread_capture_in_closure"),
    fixture!("expressions_calls", "index_capture_in_closure"),
    fixture!("expressions_calls", "member_capture_in_closure"),
    fixture!("expressions_calls", "record_update"),
    fixture!("expressions_calls", "record_update_multiple"),
    fixture!("expressions_calls", "record_update_unknown_field_fault"),
    fixture!("expressions_calls", "record_update_non_record_fault"),
    fixture!("expressions_calls", "record_update_base_checked_first"),
    fixture!("expressions_calls", "record_update_capture_in_closure"),
    fixture!("expressions_calls", "optional_access_some"),
    fixture!("expressions_calls", "optional_access_none"),
    fixture!("expressions_calls", "optional_access_null"),
    fixture!("expressions_calls", "optional_access_direct"),
    fixture!("expressions_calls", "optional_access_chain"),
    fixture!("expressions_calls", "optional_access_flattens"),
    fixture!("expressions_calls", "optional_access_capture"),
    fixture!("expressions_calls", "function_early_return"),
    fixture!("expressions_calls", "function_early_return_not_taken"),
    fixture!("expressions_calls", "function_bare_return"),
    fixture!("expressions_calls", "return_from_inside_a_loop"),
    fixture!("expressions_calls", "return_in_a_lambda_body"),
    fixture!("expressions_calls", "function_returns_a_capturing_closure"),
    fixture!("expressions_calls", "array_get_in_bounds"),
    fixture!("expressions_calls", "array_get_out_of_bounds"),
    fixture!("expressions_calls", "array_get_non_int_fault"),
    fixture!("expressions_calls", "map_get_absent"),
    fixture!("expressions_calls", "string_scalars"),
    fixture!("expressions_calls", "record_field_named_get"),
    fixture!("expressions_calls", "get_on_a_non_collection_fault"),
    fixture!("expressions_calls", "get_inside_a_lambda_body"),
    fixture!("expressions_calls", "get_on_a_captured_receiver"),
    fixture!("expressions_calls", "optional_call_some_array_get"),
    fixture!("expressions_calls", "optional_call_some_get_miss"),
    fixture!("expressions_calls", "optional_call_none_short_circuits"),
    fixture!("expressions_calls", "optional_call_record_field_closure"),
    fixture!("expressions_calls", "optional_call_some_scalars"),
    fixture!("expressions_calls", "optional_hof_array_map_some"),
    fixture!("expressions_calls", "optional_hof_array_map_none_skips_arg"),
    fixture!("expressions_calls", "optional_hof_inner_option_map_flatten"),
    fixture!("expressions_calls", "optional_hof_pipe_map_some"),
    fixture!("expressions_calls", "optional_hof_pipe_reduce_some"),
    fixture!("expressions_calls", "optional_hof_map_values_some"),
    fixture!("expressions_calls", "optional_hof_update_some_mutates"),
    fixture!("expressions_calls", "optional_hof_sortby_some_mutates"),
    // patterns_types
    fixture!("patterns_types", "mut_capture_mutation_after_creation"),
    fixture!(
        "patterns_types",
        "mut_capture_mutation_inside_visible_outside"
    ),
    fixture!("patterns_types", "mut_capture_two_closures_share_cell"),
    fixture!("patterns_types", "mut_capture_nested_closure"),
    fixture!("patterns_types", "mut_capture_compound_from_outside"),
    fixture!("patterns_types", "mut_capture_read_across_await"),
    fixture!("patterns_types", "typed_lambda_param"),
    fixture!("patterns_types", "typed_lambda_multi_param"),
    fixture!("patterns_types", "typed_lambda_param_in_hof"),
    fixture!("patterns_types", "match_guard_literal_taken"),
    fixture!("patterns_types", "match_guard_literal_falls_through"),
    fixture!("patterns_types", "match_guard_binding_taken"),
    fixture!("patterns_types", "match_guard_binding_falls_through"),
    fixture!("patterns_types", "match_guard_wildcard_falls_through"),
    fixture!("patterns_types", "match_guard_not_evaluated_until_matched"),
    fixture!("patterns_types", "match_guard_binding_miss_faults"),
    fixture!("patterns_types", "match_guard_non_bool_faults"),
    fixture!("patterns_types", "guard_captures_an_enclosing_name"),
    fixture!("patterns_types", "guard_reads_binding_and_capture"),
    fixture!("patterns_types", "match_some_binding"),
    fixture!("patterns_types", "match_none_arm"),
    fixture!("patterns_types", "match_ok_binding"),
    fixture!("patterns_types", "match_err_binding"),
    fixture!("patterns_types", "match_some_wildcard"),
    fixture!(
        "patterns_types",
        "constructor_binding_shadows_enclosing_mut"
    ),
    fixture!("patterns_types", "match_range_inclusive_in"),
    fixture!("patterns_types", "match_range_inclusive_out"),
    fixture!("patterns_types", "match_range_exclusive_boundary"),
    fixture!("patterns_types", "match_range_exclusive_in"),
    fixture!("patterns_types", "match_range_multi"),
    fixture!("patterns_types", "match_or_first_alt"),
    fixture!("patterns_types", "match_or_middle_alt"),
    fixture!("patterns_types", "match_or_miss"),
    fixture!("patterns_types", "match_or_strings"),
    fixture!("patterns_types", "match_or_lit_or_range_lit"),
    fixture!("patterns_types", "match_or_lit_or_range_in"),
    fixture!("patterns_types", "match_or_lit_or_range_miss"),
    fixture!("patterns_types", "match_or_range_exclusive_boundary"),
    fixture!("patterns_types", "match_or_two_ranges_hit"),
    fixture!("patterns_types", "match_or_two_ranges_gap"),
    fixture!("patterns_types", "match_or_range_neg_alt"),
    fixture!("patterns_types", "match_or_range_guard"),
    fixture!("patterns_types", "match_list_fixed"),
    fixture!("patterns_types", "match_list_fixed_miss"),
    fixture!("patterns_types", "match_list_head_rest"),
    fixture!("patterns_types", "match_list_tail_rest"),
    fixture!("patterns_types", "match_list_mid_rest"),
    fixture!("patterns_types", "match_list_empty"),
    fixture!("patterns_types", "match_list_rest_binds_middle"),
    fixture!("patterns_types", "list_binding_shadows_enclosing_mut"),
    fixture!("patterns_types", "match_list_ctor_elem"),
    fixture!("patterns_types", "match_list_ctor_elem_miss"),
    fixture!("patterns_types", "match_list_literal_elem"),
    fixture!("patterns_types", "match_list_literal_elem_miss"),
    fixture!("patterns_types", "match_list_nested_ctor"),
    fixture!("patterns_types", "match_list_multi_ctor"),
    fixture!("patterns_types", "match_list_ctor_guard"),
    fixture!("patterns_types", "match_record_shorthand"),
    fixture!("patterns_types", "match_record_field_pattern"),
    fixture!("patterns_types", "match_record_missing_field"),
    fixture!("patterns_types", "match_record_wildcard_field"),
    fixture!("patterns_types", "match_record_partial"),
    fixture!("patterns_types", "record_binding_shadows_enclosing_mut"),
    fixture!("patterns_types", "match_record_some_sub"),
    fixture!("patterns_types", "match_record_some_sub_miss"),
    fixture!("patterns_types", "match_record_literal_sub"),
    fixture!("patterns_types", "match_record_literal_sub_miss"),
    fixture!("patterns_types", "match_record_nested_sub"),
    fixture!("patterns_types", "match_record_ok_sub"),
    fixture!("patterns_types", "match_record_mixed_sub"),
    fixture!("patterns_types", "match_record_sub_guard_false"),
    fixture!("patterns_types", "match_typed_int_matches"),
    fixture!("patterns_types", "match_typed_string_matches"),
    fixture!("patterns_types", "match_typed_bool_matches"),
    fixture!("patterns_types", "match_typed_union_dispatch_int"),
    fixture!("patterns_types", "match_typed_union_dispatch_string"),
    fixture!("patterns_types", "typed_binding_shadows_enclosing_mut"),
    fixture!("patterns_types", "match_union_int"),
    fixture!("patterns_types", "match_union_string"),
    fixture!("patterns_types", "match_union_miss"),
    fixture!("patterns_types", "match_union_bind"),
    fixture!("patterns_types", "let_union"),
    fixture!("patterns_types", "for_union"),
    fixture!("patterns_types", "match_opt_some"),
    fixture!("patterns_types", "match_opt_none"),
    fixture!("patterns_types", "match_opt_miss"),
    fixture!("patterns_types", "match_opt_bind"),
    fixture!("patterns_types", "match_result_ok"),
    fixture!("patterns_types", "match_result_err"),
    fixture!("patterns_types", "match_result_miss"),
    fixture!("patterns_types", "match_array_int"),
    fixture!("patterns_types", "match_array_empty"),
    fixture!("patterns_types", "match_array_miss"),
    fixture!("patterns_types", "match_array_nested_opt"),
    fixture!("patterns_types", "let_opt_int"),
    fixture!("patterns_types", "for_opt_int"),
    fixture!("patterns_types", "match_record_match"),
    fixture!("patterns_types", "match_record_miss_type"),
    fixture!("patterns_types", "match_record_miss_arity"),
    fixture!("patterns_types", "match_record_extra_field"),
    fixture!("patterns_types", "match_record_bind"),
    fixture!("patterns_types", "match_record_nested"),
    fixture!("patterns_types", "let_record"),
    fixture!("patterns_types", "match_set_match"),
    fixture!("patterns_types", "match_set_miss"),
    fixture!("patterns_types", "match_set_empty"),
    fixture!("patterns_types", "match_set_nonset"),
    fixture!("patterns_types", "typed_let_int"),
    fixture!("patterns_types", "typed_let_string"),
    fixture!("patterns_types", "typed_let_bool"),
    fixture!("patterns_types", "typed_let_map_accept"),
    fixture!("patterns_types", "typed_let_map_value_fault"),
    fixture!("patterns_types", "match_map_type_accept"),
    fixture!("patterns_types", "match_map_type_falls"),
    fixture!("patterns_types", "typed_let_fn_accept"),
    fixture!("patterns_types", "typed_let_fn_fault"),
    fixture!("patterns_types", "match_fn_default_min"),
    fixture!("patterns_types", "match_fn_variadic_falls"),
    fixture!("patterns_types", "match_fn_variadic_match"),
    fixture!("patterns_types", "match_fn_builtin_shape"),
    fixture!("patterns_types", "typed_let_in_lambda"),
    fixture!("patterns_types", "typed_let_shadows_enclosing_mut"),
    fixture!("patterns_types", "typed_for_expr_collect"),
    fixture!("patterns_types", "typed_for_stmt_sum"),
    fixture!("patterns_types", "typed_for_string_collect"),
    fixture!("patterns_types", "typed_for_shadows_enclosing_mut"),
    fixture!("patterns_types", "match_guard_constructor_taken"),
    fixture!("patterns_types", "match_guard_constructor_falls_through"),
    fixture!("patterns_types", "match_guard_typed_taken"),
    fixture!("patterns_types", "match_guard_typed_falls_through"),
    fixture!("patterns_types", "match_guard_list_taken"),
    fixture!("patterns_types", "match_guard_list_falls_through"),
    fixture!("patterns_types", "match_guard_record_taken"),
    fixture!("patterns_types", "match_guard_range_taken"),
    fixture!("patterns_types", "match_guard_or_taken"),
    fixture!("patterns_types", "match_nested_some"),
    fixture!("patterns_types", "match_nested_some_none"),
    fixture!("patterns_types", "match_constructor_literal_sub"),
    fixture!("patterns_types", "match_constructor_literal_sub_miss"),
    fixture!("patterns_types", "match_nested_ok_some"),
    fixture!("patterns_types", "match_nested_some_guarded"),
    fixture!("patterns_types", "match_negative_range_in"),
    fixture!("patterns_types", "match_negative_range_out"),
    fixture!("patterns_types", "match_negative_range_both_negative"),
    fixture!("patterns_types", "integration_grades"),
    fixture!("patterns_types", "integration_options"),
    fixture!("patterns_types", "integration_orders"),
    fixture!("patterns_types", "integration_pipeline"),
    fixture!("patterns_types", "integration_loop"),
    // flow_boundaries
    fixture!("flow_boundaries", "recursion_fib"),
    fixture!("flow_boundaries", "recursion_factorial"),
    fixture!("flow_boundaries", "recursion_mutual_even_odd"),
    fixture!("flow_boundaries", "recursion_forward_sibling"),
    fixture!("flow_boundaries", "recursion_first_class"),
    fixture!("flow_boundaries", "boundary_param_scalar_fault"),
    fixture!("flow_boundaries", "boundary_param_array_fault"),
    fixture!("flow_boundaries", "boundary_param_record_fault"),
    fixture!("flow_boundaries", "boundary_param_concrete_ok"),
    fixture!("flow_boundaries", "boundary_param_typeparam_shadow_ok"),
    fixture!("flow_boundaries", "boundary_return_scalar_fault"),
    fixture!("flow_boundaries", "boundary_return_explicit_fault"),
    fixture!("flow_boundaries", "boundary_return_try_fault"),
    fixture!("flow_boundaries", "boundary_return_array_fault"),
    fixture!("flow_boundaries", "boundary_return_record_fault"),
    fixture!("flow_boundaries", "boundary_return_concrete_ok"),
    fixture!("flow_boundaries", "boundary_return_typeparam_skip"),
    fixture!("flow_boundaries", "boundary_return_unit_skip"),
    fixture!("flow_boundaries", "boundary_return_nested_unit_skip"),
    fixture!("flow_boundaries", "boundary_param_unit_skip"),
    fixture!("flow_boundaries", "boundary_variadic_fault"),
    fixture!("flow_boundaries", "boundary_variadic_ok"),
    fixture!("flow_boundaries", "boundary_variadic_fixed_first"),
    fixture!("flow_boundaries", "defer_lifo_and_body"),
    fixture!("flow_boundaries", "block_defer_normal"),
    fixture!("flow_boundaries", "block_defer_nested_lifo"),
    fixture!("flow_boundaries", "block_defer_return_crosses"),
    fixture!("flow_boundaries", "block_defer_question_crosses"),
    fixture!("flow_boundaries", "block_defer_loop_per_iteration"),
    fixture!("flow_boundaries", "block_defer_continue_crosses"),
    fixture!("flow_boundaries", "block_defer_break_crosses"),
    fixture!("flow_boundaries", "block_defer_lambda_body"),
    fixture!("flow_boundaries", "block_defer_match_arm"),
    fixture!("flow_boundaries", "block_defer_case_arm_return"),
    fixture!("flow_boundaries", "block_defer_loop_no_tail"),
    fixture!("flow_boundaries", "block_defer_lambda_no_inherit"),
    fixture!("flow_boundaries", "block_defer_return_value_first"),
    fixture!("flow_boundaries", "block_defer_return_fault_no_drain"),
    fixture!("flow_boundaries", "defer_captures_mutable_local"),
    fixture!("flow_boundaries", "defer_lifo_with_mutable"),
    fixture!("flow_boundaries", "nested_fn_defer_captures_outer"),
    fixture!("flow_boundaries", "defer_runs_on_return"),
    fixture!("flow_boundaries", "defer_runs_on_question"),
    fixture!("flow_boundaries", "defer_error_routed"),
    fixture!("flow_boundaries", "fwd_ref_call_across_statement"),
    fixture!("flow_boundaries", "fwd_ref_mutual_across_statement"),
    fixture!("flow_boundaries", "fwd_ref_early_call_unbound"),
    fixture!("flow_boundaries", "top_fn_shadowed_by_block_local"),
    fixture!("flow_boundaries", "spread_call_variadic"),
    fixture!("flow_boundaries", "spread_call_fixed_then_variadic"),
    // nominals_protocols
    fixture!("nominals_protocols", "enum_construct_render"),
    fixture!("nominals_protocols", "enum_match_red"),
    fixture!("nominals_protocols", "enum_match_blue"),
    fixture!("nominals_protocols", "enum_nominal_eq"),
    fixture!("nominals_protocols", "enum_nominal_distinct"),
    fixture!("nominals_protocols", "enum_match_wildcard"),
    fixture!("nominals_protocols", "enum_match_guard"),
    fixture!(
        "nominals_protocols",
        "enum_bare_name_binds_non_enum_scrutinee"
    ),
    fixture!("nominals_protocols", "enum_payload_construct_render"),
    fixture!("nominals_protocols", "enum_payload_match_extract"),
    fixture!("nominals_protocols", "enum_payload_mixed"),
    fixture!("nominals_protocols", "enum_or_bind_payload"),
    fixture!("nominals_protocols", "enum_or_bind_guard"),
    fixture!("nominals_protocols", "enum_or_bind_nested_some"),
    fixture!("nominals_protocols", "enum_payload_literal_and_wildcard"),
    fixture!("nominals_protocols", "enum_payload_string"),
    fixture!("nominals_protocols", "enum_payload_eq"),
    fixture!("nominals_protocols", "enum_nested_enum_payload"),
    fixture!("nominals_protocols", "enum_nonenum_union_payload"),
    fixture!("nominals_protocols", "selfhost_arena_evaluator"),
    fixture!("nominals_protocols", "enum_multi_payload_construct_render"),
    fixture!("nominals_protocols", "enum_multi_payload_match_extract"),
    fixture!("nominals_protocols", "enum_recursive_expr_tree"),
    fixture!("nominals_protocols", "enum_mutual_recursion"),
    fixture!("nominals_protocols", "enum_multi_payload_eq"),
    fixture!("nominals_protocols", "record_construct_render"),
    fixture!("nominals_protocols", "record_pattern_destructure"),
    fixture!("nominals_protocols", "record_defaults"),
    fixture!("nominals_protocols", "record_eq"),
    fixture!("nominals_protocols", "record_spread_update"),
    fixture!(
        "nominals_protocols",
        "record_spread_external_malformed_fields"
    ),
    fixture!("nominals_protocols", "record_spread_keeps_default_origin"),
    fixture!("nominals_protocols", "record_spread_eval_order"),
    fixture!("nominals_protocols", "record_spread_wrong_id_fault"),
    fixture!(
        "nominals_protocols",
        "record_structural_spread_shadow_fault"
    ),
    fixture!(
        "nominals_protocols",
        "record_spread_generic_expected_context"
    ),
    fixture!("nominals_protocols", "record_spread_shallow_array_alias"),
    fixture!("nominals_protocols", "record_with_enum_field"),
    fixture!("nominals_protocols", "enum_with_record_payload"),
    fixture!("nominals_protocols", "record_field_access_typed"),
    fixture!("nominals_protocols", "record_empty_and_all_default"),
    fixture!("nominals_protocols", "record_callable_field"),
    fixture!("nominals_protocols", "derive_order_audit_decl_order"),
    fixture!("nominals_protocols", "protocol_show_derived_record"),
    fixture!("nominals_protocols", "protocol_generic_bound_show"),
    fixture!("nominals_protocols", "protocol_generic_bound_forwarding"),
    fixture!("nominals_protocols", "protocol_generic_bound_callback"),
    fixture!(
        "nominals_protocols",
        "protocol_generic_bound_json_stringify"
    ),
    fixture!("nominals_protocols", "protocol_eq_derived_record"),
    fixture!("nominals_protocols", "protocol_order_derived_record"),
    fixture!("nominals_protocols", "protocol_order_derived_enum"),
    fixture!(
        "nominals_protocols",
        "derive_record_with_comparable_enum_member"
    ),
    fixture!("nominals_protocols", "protocol_show_manual_impl"),
    fixture!("nominals_protocols", "protocol_user_manual_impl"),
    fixture!("nominals_protocols", "protocol_manual_impl_fault"),
    fixture!("nominals_protocols", "protocol_manual_impl_calls_sibling"),
    fixture!("nominals_protocols", "protocol_manual_args_left_to_right"),
    fixture!("nominals_protocols", "protocol_manual_hoisted"),
    fixture!(
        "nominals_protocols",
        "protocol_manual_eq_does_not_change_operator"
    ),
    fixture!("nominals_protocols", "protocol_manual_module_value_capture"),
    fixture!("nominals_protocols", "protocol_manual_cooperative_call"),
    fixture!("nominals_protocols", "newtype_construct_render"),
    fixture!("nominals_protocols", "newtype_value_unwrap_use"),
    fixture!("nominals_protocols", "newtype_first_class_value_bridge"),
    fixture!("nominals_protocols", "newtype_pattern_destructure"),
    fixture!("nominals_protocols", "newtype_eq"),
    fixture!("nominals_protocols", "newtype_over_string"),
    fixture!("nominals_protocols", "newtype_value_on_nonnewtype_fault"),
    fixture!("nominals_protocols", "newtype_as_record_field"),
    fixture!("nominals_protocols", "newtype_ctor_wrong_arity_fault"),
    fixture!("nominals_protocols", "method_record_self_field"),
    fixture!("nominals_protocols", "method_module_value_capture"),
    fixture!("nominals_protocols", "method_mutable_module_value_capture"),
    fixture!("nominals_protocols", "method_module_value_preinit_fault"),
    fixture!(
        "nominals_protocols",
        "method_same_name_different_signatures"
    ),
    fixture!("nominals_protocols", "method_calls_sibling_method"),
    fixture!("nominals_protocols", "method_returns_new_value"),
    fixture!("nominals_protocols", "method_on_enum"),
    fixture!("nominals_protocols", "method_on_newtype"),
    fixture!("nominals_protocols", "method_with_arg"),
    fixture!("nominals_protocols", "method_named_arg"),
    fixture!("nominals_protocols", "method_defaulted_arg"),
    fixture!("nominals_protocols", "method_spread_variadic"),
    fixture!(
        "nominals_protocols",
        "method_receiver_once_args_left_to_right"
    ),
    fixture!("nominals_protocols", "method_on_wrong_receiver_fault"),
    fixture!("nominals_protocols", "nominal_record_order_single"),
    fixture!("nominals_protocols", "nominal_record_order_two_field"),
    fixture!("nominals_protocols", "nominal_record_order_string_field"),
    fixture!("nominals_protocols", "nominal_enum_order"),
    fixture!("nominals_protocols", "nominal_newtype_order"),
    fixture!("nominals_protocols", "sorted_records"),
    fixture!("nominals_protocols", "sorted_enums"),
    fixture!("nominals_protocols", "sorted_by_int_key"),
    fixture!("nominals_protocols", "sorted_by_string_key"),
    fixture!("nominals_protocols", "sorted_by_generic_identity_key"),
    fixture!("nominals_protocols", "sorted_by_stable_ties"),
    fixture!("nominals_protocols", "sorted_stable_ties"),
    fixture!("nominals_protocols", "sorted_nonorderable_fault"),
    // collections_comprehensions
    fixture!("collections_comprehensions", "match_guard_pass"),
    fixture!("collections_comprehensions", "match_guard_fail"),
    fixture!("collections_comprehensions", "match_guard_payload"),
    fixture!("collections_comprehensions", "default_param_omitted"),
    fixture!("collections_comprehensions", "default_param_supplied"),
    fixture!("collections_comprehensions", "default_param_eval_order"),
    fixture!("collections_comprehensions", "if_let_some"),
    fixture!("collections_comprehensions", "if_let_none"),
    fixture!("collections_comprehensions", "if_let_binding_scope"),
    fixture!("collections_comprehensions", "while_let_drain"),
    fixture!("collections_comprehensions", "while_let_zero_iterations"),
    fixture!(
        "collections_comprehensions",
        "while_let_scrutinee_once_per_attempt"
    ),
    fixture!(
        "collections_comprehensions",
        "while_let_scrutinee_controls_own_loop"
    ),
    fixture!("collections_comprehensions", "set_literal"),
    fixture!("collections_comprehensions", "set_literal_collapse"),
    fixture!("collections_comprehensions", "set_literal_strings"),
    fixture!("collections_comprehensions", "set_literal_empty_annotated"),
    fixture!("collections_comprehensions", "map_literal_keys"),
    fixture!("collections_comprehensions", "map_literal_get"),
    fixture!("collections_comprehensions", "map_literal_int_keys"),
    fixture!("collections_comprehensions", "map_literal_empty_annotated"),
    fixture!("collections_comprehensions", "map_literal_dup_key_fault"),
    fixture!("collections_comprehensions", "set_literal_enum_key"),
    fixture!("collections_comprehensions", "map_literal_enum_payload_key"),
    fixture!(
        "collections_comprehensions",
        "map_literal_bad_enum_payload_key_fault"
    ),
    fixture!(
        "collections_comprehensions",
        "map_literal_nominal_record_key"
    ),
    fixture!(
        "collections_comprehensions",
        "set_literal_nominal_record_key"
    ),
    fixture!(
        "collections_comprehensions",
        "map_literal_bad_nominal_record_key_fault"
    ),
    fixture!("collections_comprehensions", "set_literal_newtype_key"),
    fixture!("collections_comprehensions", "map_literal_newtype_key"),
    fixture!(
        "collections_comprehensions",
        "set_literal_newtype_distinct_from_inner"
    ),
    fixture!(
        "collections_comprehensions",
        "set_literal_bad_newtype_key_fault"
    ),
    fixture!("collections_comprehensions", "map_free_fn_regression"),
    fixture!("collections_comprehensions", "map_identifier_regression"),
    fixture!("collections_comprehensions", "set_identifier_regression"),
    fixture!(
        "collections_comprehensions",
        "set_literal_evaluation_order_and_first_slot"
    ),
    fixture!(
        "collections_comprehensions",
        "map_literal_evaluates_all_entries_before_duplicate_fault"
    ),
    fixture!("collections_comprehensions", "comp_array_squares"),
    fixture!("collections_comprehensions", "comp_array_filter"),
    fixture!("collections_comprehensions", "comp_array_nested"),
    fixture!("collections_comprehensions", "comp_array_nested_filter"),
    fixture!("collections_comprehensions", "comp_array_hygiene_acc"),
    fixture!("collections_comprehensions", "comp_set_collapse"),
    fixture!("collections_comprehensions", "comp_map_keys"),
    fixture!("collections_comprehensions", "comp_map_get"),
    fixture!("collections_comprehensions", "comp_map_dup_key_fault"),
    fixture!("collections_comprehensions", "comp_array_body_loopvar"),
    fixture!(
        "collections_comprehensions",
        "comp_for_nominal_record_pattern"
    ),
    fixture!("collections_comprehensions", "comp_for_range_pattern"),
    fixture!("collections_comprehensions", "comp_for_or_pattern"),
    fixture!(
        "collections_comprehensions",
        "comp_lambda_captures_loop_var"
    ),
    fixture!("collections_comprehensions", "comp_array_empty_annotated"),
    fixture!("collections_comprehensions", "comp_nested_clause_shadowing"),
    fixture!("collections_comprehensions", "comp_clause_evaluation_order"),
    fixture!(
        "collections_comprehensions",
        "comp_pattern_mismatch_fault_timing"
    ),
    fixture!(
        "collections_comprehensions",
        "comp_map_evaluates_all_pairs_before_duplicate_fault"
    ),
    fixture!("collections_comprehensions", "test_assert_free_pass"),
    fixture!("collections_comprehensions", "test_assert_free_fault"),
    fixture!(
        "collections_comprehensions",
        "nominal_record_mutable_default_current_binding"
    ),
    fixture!(
        "collections_comprehensions",
        "nominal_record_effectful_defaults_order_and_skip"
    ),
];
