// @generated by unicode-gen from CaseFolding.txt and UnicodeData.txt
// (UCD 16.0.0, vendored under tools/unicode-gen/data). Do not edit.

mod ccc;
mod decomp;
mod fold;

pub use ccc::CCC;
pub use decomp::DECOMP;
pub use fold::FOLD;
